SELECT        TOP (100) PERCENT REPORT_DATE, PEER, STATUS, ADAPTER, COUNT(*) AS Count
FROM            dbo.LOG_GRID
GROUP BY REPORT_DATE, PEER, STATUS, ADAPTER
HAVING        (STATUS = 'ERROR')
ORDER BY REPORT_DATE, Count DESC



SELECT        TOP (100) PERCENT REPORT_TIMESTAMP AS TIME, METRIC_INSTANCE AS PEER, METRIC_VALUE AS Requests
FROM            dbo.LOG_HEALTH
WHERE        (METRIC_NAME = 'NUMBER_OF_UNANSWERED_REQUESTS')


